
sensor:  
  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_voltage
    name: "array_rated_voltage"
    address: 0x3000
    skip_updates: 60
    unit_of_measurement: "V"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_current
    name: "array_rated_current"
    address: 0x3001
    unit_of_measurement: "A"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_power
    name: "array_rated_power"
    address: 0x3002
    register_count: 2
    unit_of_measurement: "W"
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD_R
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_rated_voltage
    name: "battery_rated_voltage"
    address: 0x3004
    unit_of_measurement: "V"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_rated_current
    name: "battery_rated_current"
    address: 0x3005
    unit_of_measurement: "A"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_rated_power
    name: "battery_rated_power"
    address: 0x3006
    unit_of_measurement: "W"
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD_R
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_mode
    name: "charging_mode"
    address: 0x3008
    unit_of_measurement: ""
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: epever
    id: rated_current_of_load
    name: "rated_current_of_load"
    address: 0x300E
    skip_updates: 60
    unit_of_measurement: "A"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
